import Head from "next/head";
import { Card, Header, Hero } from "nhsuk-react-components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Nextjs NHSUK</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header transactional>
        <Header.Container>
          <Header.Logo href='/' />
          <Header.ServiceName href='/'>Register with a GP</Header.ServiceName>
        </Header.Container>
      </Header>
      <Hero imageSrc='https://assets.nhs.uk/prod/images/S_0818_homepage_hero_1_F0147446.width-1000.jpg'>
        <Hero.Heading>We&apos;re here for you.</Hero.Heading>
        <Hero.Text>
          Helping you take control of your health and wellbeing.
        </Hero.Text>
      </Hero>
      <div className='nhsuk-width-container nhsuk-u-margin-top-9'>
        <main className='nhsuk-main-wrapper' id='maincontent' role='main'>
          <div className='nhsuk-grid-row'>
            <div className='nhsuk-grid-column-two-thirds'>
              <h2>NHSUK SSR With NextJS</h2>
              <Card.Group>
                <Card.GroupItem width='one-half'>
                  <Card clickable>
                    <Card.Content>
                      <Card.Heading className='nhsuk-heading-m'>
                        <Card.Link href='#'>
                          Introduction to care and support
                        </Card.Link>
                      </Card.Heading>
                      <Card.Description>
                        A quick guide for people who have care and support needs
                        and their carers
                      </Card.Description>
                    </Card.Content>
                  </Card>
                </Card.GroupItem>
                <Card.GroupItem width='one-half'>
                  <Card clickable>
                    <Card.Content>
                      <Card.Heading className='nhsuk-heading-m'>
                        <Card.Link href='#'>
                          Help from social services and charities
                        </Card.Link>
                      </Card.Heading>
                      <Card.Description>
                        Includes helplines, needs assessments, advocacy and
                        reporting abuse
                      </Card.Description>
                    </Card.Content>
                  </Card>
                </Card.GroupItem>
                <Card.GroupItem width='one-half'>
                  <Card clickable>
                    <Card.Content>
                      <Card.Heading className='nhsuk-heading-m'>
                        <Card.Link href='#'>Money, work and benefits</Card.Link>
                      </Card.Heading>
                      <Card.Description>
                        How to pay for care and support, and where you can get
                        help with costs
                      </Card.Description>
                    </Card.Content>
                  </Card>
                </Card.GroupItem>
                <Card.GroupItem width='one-half'>
                  <Card clickable>
                    <Card.Content>
                      <Card.Heading className='nhsuk-heading-m'>
                        <Card.Link href='#'>
                          Care after a hospital stay
                        </Card.Link>
                      </Card.Heading>
                      <Card.Description>
                        Includes hospital discharge and care and support
                        afterwards
                      </Card.Description>
                    </Card.Content>
                  </Card>
                </Card.GroupItem>
              </Card.Group>
            </div>
          </div>
        </main>
      </div>
    </>
  );
}
